-- MySQL Script generated by MySQL Workbench
-- ter 13 nov 2018 23:52:21 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `descricao_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEndereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoEndereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoEndereco` (
  `id_tipo_endereco` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_endereco`),
  UNIQUE INDEX `id_tipo_endereco_UNIQUE` (`id_tipo_endereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `id_estado_UNIQUE` (`id_estado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NOT NULL,
  `Estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  UNIQUE INDEX `id_cidade_UNIQUE` (`id_cidade` ASC),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_id_estado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_id_estado`)
    REFERENCES `mydb`.`Estado` (`id_estado`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `id_bairro` INT NOT NULL AUTO_INCREMENT,
  `nome_bairro` VARCHAR(45) NOT NULL,
  `Cidade_id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_bairro`),
  UNIQUE INDEX `id_bairro_UNIQUE` (`id_bairro` ASC),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_id_cidade` ASC),
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_id_cidade`)
    REFERENCES `mydb`.`Cidade` (`id_cidade`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rua` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rua` (
  `id_rua` INT NOT NULL AUTO_INCREMENT,
  `nome_rua` VARCHAR(45) NOT NULL,
  `Bairro_id_bairro` INT NOT NULL,
  PRIMARY KEY (`id_rua`),
  UNIQUE INDEX `id_rua_UNIQUE` (`id_rua` ASC),
  INDEX `fk_Rua_Bairro1_idx` (`Bairro_id_bairro` ASC),
  CONSTRAINT `fk_Rua_Bairro1`
    FOREIGN KEY (`Bairro_id_bairro`)
    REFERENCES `mydb`.`Bairro` (`id_bairro`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `nome_endereco` VARCHAR(45) NOT NULL,
  `TipoEndereco_id_tipo_endereco` INT NOT NULL,
  `numero_endereco` DECIMAL(10,0) NULL,
  `complemento_endereco` VARCHAR(45) NULL,
  `Rua_id_rua` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC),
  INDEX `fk_Endereco_TipoEndereco1_idx` (`TipoEndereco_id_tipo_endereco` ASC),
  INDEX `fk_Endereco_Rua1_idx` (`Rua_id_rua` ASC),
  CONSTRAINT `fk_Endereco_TipoEndereco1`
    FOREIGN KEY (`TipoEndereco_id_tipo_endereco`)
    REFERENCES `mydb`.`TipoEndereco` (`id_tipo_endereco`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Rua1`
    FOREIGN KEY (`Rua_id_rua`)
    REFERENCES `mydb`.`Rua` (`id_rua`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sexo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `nome_sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sexo`),
  UNIQUE INDEX `id_sexo_UNIQUE` (`id_sexo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escolaridade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Escolaridade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridade` (
  `id_escolaridade` INT NOT NULL AUTO_INCREMENT,
  `nome_escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_escolaridade`),
  UNIQUE INDEX `id_escolaridade_UNIQUE` (`id_escolaridade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  `descricao_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`),
  UNIQUE INDEX `id_cargo_UNIQUE` (`id_cargo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoCivil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoCivil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `nome_estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_civil`),
  UNIQUE INDEX `idEstadoCivil_UNIQUE` (`id_estado_civil` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pais`),
  UNIQUE INDEX `id_pais_UNIQUE` (`id_pais` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id_func` INT NOT NULL AUTO_INCREMENT,
  `cpf_func` DECIMAL(10,0) NOT NULL,
  `nome_func` VARCHAR(45) NOT NULL,
  `carteira_trabalho_func` DECIMAL(10,0) NOT NULL,
  `salario_func` FLOAT NOT NULL,
  `Endereco_id_endereco` INT NOT NULL,
  `nome_do_pai_func` VARCHAR(45) NULL,
  `nome_da_mae_func` VARCHAR(45) NOT NULL,
  `rg_func` DECIMAL(10,0) NOT NULL,
  `email_func` VARCHAR(45) NOT NULL,
  `Sexo_id_sexo` INT NOT NULL,
  `Escolaridade_id_escolaridade` INT NOT NULL,
  `Cargo_id_cargo` INT NOT NULL,
  `EstadoCivil_id_estado_civil` INT NOT NULL,
  `Pais_id_pais` INT NOT NULL,
  `Estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_func`, `cpf_func`),
  UNIQUE INDEX `cpf_func_UNIQUE` (`cpf_func` ASC),
  UNIQUE INDEX `carteira_trabalho_func_UNIQUE` (`carteira_trabalho_func` ASC),
  UNIQUE INDEX `id_func_UNIQUE` (`id_func` ASC),
  INDEX `fk_Funcionario_Endereco1_idx` (`Endereco_id_endereco` ASC),
  INDEX `fk_Funcionario_Sexo1_idx` (`Sexo_id_sexo` ASC),
  INDEX `fk_Funcionario_Escolaridade1_idx` (`Escolaridade_id_escolaridade` ASC),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_id_cargo` ASC),
  INDEX `fk_Funcionario_EstadoCivil1_idx` (`EstadoCivil_id_estado_civil` ASC),
  INDEX `fk_Funcionario_Pais1_idx` (`Pais_id_pais` ASC),
  INDEX `fk_Funcionario_Estado1_idx` (`Estado_id_estado` ASC),
  CONSTRAINT `fk_Funcionario_Endereco1`
    FOREIGN KEY (`Endereco_id_endereco`)
    REFERENCES `mydb`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Sexo1`
    FOREIGN KEY (`Sexo_id_sexo`)
    REFERENCES `mydb`.`Sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Escolaridade1`
    FOREIGN KEY (`Escolaridade_id_escolaridade`)
    REFERENCES `mydb`.`Escolaridade` (`id_escolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_id_cargo`)
    REFERENCES `mydb`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id_estado_civil`)
    REFERENCES `mydb`.`EstadoCivil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Pais1`
    FOREIGN KEY (`Pais_id_pais`)
    REFERENCES `mydb`.`Pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Estado1`
    FOREIGN KEY (`Estado_id_estado`)
    REFERENCES `mydb`.`Estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Andar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Andar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Andar` (
  `idAndar` INT NOT NULL,
  `numero_andar` INT NULL,
  `descricao_andar` VARCHAR(45) NULL,
  PRIMARY KEY (`idAndar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `numero_mesa` INT NOT NULL,
  `Andar_id_andar` INT NOT NULL,
  PRIMARY KEY (`id_mesa`),
  UNIQUE INDEX `id_mesa_UNIQUE` (`id_mesa` ASC),
  UNIQUE INDEX `numero_mesa_UNIQUE` (`numero_mesa` ASC),
  INDEX `fk_Mesa_Andar1_idx` (`Andar_id_andar` ASC),
  CONSTRAINT `fk_Mesa_Andar1`
    FOREIGN KEY (`Andar_id_andar`)
    REFERENCES `mydb`.`Andar` (`idAndar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf_cliente` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoTelefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoTelefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoTelefone` (
  `id_tipo_telefone` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_telefone`),
  UNIQUE INDEX `id_tipo_telefone_UNIQUE` (`id_tipo_telefone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero_telefone` DECIMAL(10,0) NOT NULL,
  `TipoTelefone_id_tipo_telefone` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  UNIQUE INDEX `id_telefone_UNIQUE` (`id_telefone` ASC),
  INDEX `fk_Telefone_TipoTelefone1_idx` (`TipoTelefone_id_tipo_telefone` ASC),
  CONSTRAINT `fk_Telefone_TipoTelefone1`
    FOREIGN KEY (`TipoTelefone_id_tipo_telefone`)
    REFERENCES `mydb`.`TipoTelefone` (`id_tipo_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelefoneFuncionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TelefoneFuncionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TelefoneFuncionario` (
  `id_telefone_func` INT NOT NULL AUTO_INCREMENT,
  `Telefone_id_telefone` INT NOT NULL,
  `Funcionario_id_func` INT NOT NULL,
  PRIMARY KEY (`id_telefone_func`),
  UNIQUE INDEX `id_telefone_garcom_UNIQUE` (`id_telefone_func` ASC),
  INDEX `fk_TelefoneFuncionario_Telefone1_idx` (`Telefone_id_telefone` ASC),
  INDEX `fk_TelefoneFuncionario_Funcionario1_idx` (`Funcionario_id_func` ASC),
  CONSTRAINT `fk_TelefoneFuncionario_Telefone1`
    FOREIGN KEY (`Telefone_id_telefone`)
    REFERENCES `mydb`.`Telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TelefoneFuncionario_Funcionario1`
    FOREIGN KEY (`Funcionario_id_func`)
    REFERENCES `mydb`.`Funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelefoneCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TelefoneCliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TelefoneCliente` (
  `id_telefone_cliente` INT NOT NULL AUTO_INCREMENT,
  `Telefone_id_telefone` INT NOT NULL,
  `Cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone_cliente`),
  UNIQUE INDEX `id_telefone_cliente_UNIQUE` (`id_telefone_cliente` ASC),
  INDEX `fk_TelefoneCliente_Telefone1_idx` (`Telefone_id_telefone` ASC),
  INDEX `fk_TelefoneCliente_Cliente1_idx` (`Cliente_id_cliente` ASC),
  CONSTRAINT `fk_TelefoneCliente_Telefone1`
    FOREIGN KEY (`Telefone_id_telefone`)
    REFERENCES `mydb`.`Telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TelefoneCliente_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormatoPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FormatoPagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FormatoPagamento` (
  `id_formato_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome_formato_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_formato_pagamento`),
  UNIQUE INDEX `id_formato_pagamento_UNIQUE` (`id_formato_pagamento` ASC),
  UNIQUE INDEX `nome_formato_pagamento_UNIQUE` (`nome_formato_pagamento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `Valor` FLOAT NOT NULL,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `FormatoPagamento_id_formato_pagamento` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  UNIQUE INDEX `id_pagamento_UNIQUE` (`id_pagamento` ASC),
  INDEX `fk_Pagamento_FormatoPagamento1_idx` (`FormatoPagamento_id_formato_pagamento` ASC),
  CONSTRAINT `fk_Pagamento_FormatoPagamento1`
    FOREIGN KEY (`FormatoPagamento_id_formato_pagamento`)
    REFERENCES `mydb`.`FormatoPagamento` (`id_formato_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `cnpj_fornecedor` DECIMAL(10,0) NOT NULL,
  `nome_fornecedor` VARCHAR(45) NULL,
  `email_fornecedor` VARCHAR(45) NULL,
  `Endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor`, `cnpj_fornecedor`),
  UNIQUE INDEX `id_fornecedor_UNIQUE` (`id_fornecedor` ASC),
  INDEX `fk_Fornecedor_Endereco1_idx` (`Endereco_id_endereco` ASC),
  CONSTRAINT `fk_Fornecedor_Endereco1`
    FOREIGN KEY (`Endereco_id_endereco`)
    REFERENCES `mydb`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelefoneFornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TelefoneFornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TelefoneFornecedor` (
  `id_telefone_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `Telefone_id_telefone` INT NOT NULL,
  `Fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_telefone_fornecedor`),
  UNIQUE INDEX `id_telefone_fornecedor_UNIQUE` (`id_telefone_fornecedor` ASC),
  INDEX `fk_TelefoneFornecedor_Telefone1_idx` (`Telefone_id_telefone` ASC),
  INDEX `fk_TelefoneFornecedor_Fornecedor1_idx` (`Fornecedor_id_fornecedor` ASC),
  CONSTRAINT `fk_TelefoneFornecedor_Telefone1`
    FOREIGN KEY (`Telefone_id_telefone`)
    REFERENCES `mydb`.`Telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TelefoneFornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id_fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_pedido` FLOAT NOT NULL,
  `data_pedido` DATE NULL,
  `Pagamento_id_pagamento` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC),
  INDEX `fk_Pedido_Pagamento1_idx` (`Pagamento_id_pagamento` ASC),
  CONSTRAINT `fk_Pedido_Pagamento1`
    FOREIGN KEY (`Pagamento_id_pagamento`)
    REFERENCES `mydb`.`Pagamento` (`id_pagamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `descricao_produto` VARCHAR(45) NULL,
  `preco_produto` FLOAT NULL,
  `qtd_produto_vendidos` INT NULL,
  `qtd_produto_estoque` INT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC),
  INDEX `fk_Produto_Categoria1_idx` (`Categoria_id_categoria` ASC),
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `mydb`.`Categoria` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PedidoProduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PedidoProduto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PedidoProduto` (
  `id_pedido_produto` INT NOT NULL AUTO_INCREMENT,
  `Produto_id_produto` INT NOT NULL,
  `Pedido_id_pedido` INT NOT NULL,
  `Produto_id_produto1` INT NOT NULL,
  PRIMARY KEY (`id_pedido_produto`),
  UNIQUE INDEX `id_pedido_produto_UNIQUE` (`id_pedido_produto` ASC),
  INDEX `fk_PedidoProduto_Pedido1_idx` (`Pedido_id_pedido` ASC),
  INDEX `fk_PedidoProduto_Produto1_idx` (`Produto_id_produto1` ASC),
  CONSTRAINT `fk_PedidoProduto_Pedido1`
    FOREIGN KEY (`Pedido_id_pedido`)
    REFERENCES `mydb`.`Pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PedidoProduto_Produto1`
    FOREIGN KEY (`Produto_id_produto1`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `Mesa_id_mesa` INT NOT NULL,
  `Pedido_id_pedido` INT NOT NULL,
  `Funcionario_id_func` INT NOT NULL,
  `Cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  UNIQUE INDEX `id_tipo_pedido_UNIQUE` (`id_venda` ASC),
  INDEX `fk_Venda_Mesa1_idx` (`Mesa_id_mesa` ASC),
  INDEX `fk_Venda_Pedido1_idx` (`Pedido_id_pedido` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_id_func` ASC),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_id_cliente` ASC),
  CONSTRAINT `fk_Venda_Mesa1`
    FOREIGN KEY (`Mesa_id_mesa`)
    REFERENCES `mydb`.`Mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Pedido1`
    FOREIGN KEY (`Pedido_id_pedido`)
    REFERENCES `mydb`.`Pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_id_func`)
    REFERENCES `mydb`.`Funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente`)
    REFERENCES `mydb`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reposicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reposicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reposicao` (
  `id_reposicao` INT NOT NULL AUTO_INCREMENT,
  `Pedido_id_pedido` INT NOT NULL,
  `Fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_reposicao`),
  UNIQUE INDEX `id_reposicao_UNIQUE` (`id_reposicao` ASC),
  INDEX `fk_Reposicao_Pedido1_idx` (`Pedido_id_pedido` ASC),
  INDEX `fk_Reposicao_Fornecedor1_idx` (`Fornecedor_id_fornecedor` ASC),
  CONSTRAINT `fk_Reposicao_Pedido1`
    FOREIGN KEY (`Pedido_id_pedido`)
    REFERENCES `mydb`.`Pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reposicao_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id_fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`id_fornecedor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Categoria` (`id_categoria`, `nome_categoria`, `descricao_categoria`) VALUES (1, 'Massas', 'Macarrões, Lasanhas');
INSERT INTO `mydb`.`Categoria` (`id_categoria`, `nome_categoria`, `descricao_categoria`) VALUES (2, 'Bebidas', 'Sucos, Refrigerantes');
INSERT INTO `mydb`.`Categoria` (`id_categoria`, `nome_categoria`, `descricao_categoria`) VALUES (3, 'Saladas', 'Folhas e etc');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Produto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (1, 'Penne', 'Macarrão Penne', 15, 0, 10, 1);
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (2, 'Espaguete', 'Macarrão Espaguete', 14, 1, 5, 1);
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (3, 'Coca-Cola', 'Refri Coca', 4, 20, 50, 2);
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (4, 'Suco de Laranja', 'Uma Delicia', 5, 65, 99, 2);
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (5, 'Salada de alface', 'Muitas Folhas de Alface', 8, 4, 44, 3);
INSERT INTO `mydb`.`Produto` (`id_produto`, `nome_produto`, `descricao_produto`, `preco_produto`, `qtd_produto_vendidos`, `qtd_produto_estoque`, `Categoria_id_categoria`) VALUES (6, 'Salada de repolho', 'Vários tipos de repolho', 9, 8, 18, 3);

COMMIT;

